#!groovy
pipeline {

  agent any

  stages {
    stage ('Build') {
      steps {
        dir('user-service') {
          sh "../mvnw clean verify"
        }
      }
    }
    stage('Deploy') {
      when {
        branch 'master'
      }
      steps {
        echo 'Deploying to prod now...'
      }
    }
  }

}