#!groovy
pipeline {

  agent any

  stages {
    stage ('Build') {
      steps {
        sh "./mvnw clean verify"
      }
    }
    stage('Deploy') {
      when {
        branch 'master'
      }
      steps {
        echo 'Deploying to prod now...'
      }
    }
  }

}